apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-depl
  labels:
    app: kafka-consumer-spec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: mauxkconsumer
        image: mauxkconsumer:1.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        
