version: '3.1'

services:
  kproducer:
    image: mauxkproducer:1.0.0
    ports:
      - 8081:8081

  kconsumerA:
    image: mauxkconsumer:1.0.0
    environment:
      TOPIC_NAME: sample-p1
      CONSUMER_GROUP: group-one
      KAFKA_TOPIC_PARTITIONS: 1
          
  kconsumerB:
    image: mauxkconsumer:1.0.0
    environment:
      TOPIC_NAME: sample-p1
      CONSUMER_GROUP: group-two
      KAFKA_TOPIC_PARTITIONS: 1

networks:
  default:
    external: true
    name: docker_kafka_test
