version: '3.1'

services:
  logstash:
#    image: logstash:7.16.1
    image: docker.elastic.co/logstash/logstash:7.16.1
    volumes:
      - ./logstash/config:/config-dir
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    command: logstash -f /config-dir/kafka-pipeline.conf
    networks:
      - kafka_test

networks:
  kafka_test:
    driver: bridge
    
