version: '3.1'

services:
  kproducer:
    image: mauxkproducer:1.0.0
    ports:
      - 8081:8081

  kconsumerA:
    image: mauxkconsumer:1.0.0
    environment:
      CONSUMER_TYPE: red
          
  kconsumerB:
    image: mauxkconsumer:1.0.0
    environment:
      CONSUMER_TYPE: green

networks:
  default:
    external: true
    name: docker_kafka_test
